"""Response Signature — bundled ARGO plugin.

Appends a short provenance footer to every agent response so recipients know it was generated by ARGO.
"""

from __future__ import annotations

from argo_brain.plugin.api import ArgoPlugin


class ResponseSignaturePlugin(ArgoPlugin):
    """Records that responses should carry a provenance footer."""

    name = "response-signature"
    version = "1.0.0"
    description = "Adds an ARGO provenance footer to responses."

    FOOTER = "\n\n-- Generated by ARGO Agent"

    def sign(self, content: str) -> str:
        """Return content with the provenance footer appended."""
        if content.rstrip().endswith(self.FOOTER.strip()):
            return content
        return content.rstrip() + self.FOOTER

    async def on_response(self, user_id: str, content: str, model: str) -> None:
        self.event("response.signed", user_id=user_id, model=model)
